image: java:11

stages:
  - build
  - test

before_script:
  - chmod +x gradlew

compile:
  stage: compile
  script: ./gradlew compileJava

test:
  stage: test
  script: ./gradlew check

build:
  stage: build
  script: ./gradlew bootJar
  artifacts:
    paths:
      - build/libs/microservice-template-1.0.0-SNAPSHOT.jar
