image: java:11

stages:
  - build
  - docker-build
  - docker-push
  - docker-deploy-swarm

before_script:
  - chmod +x gradlew

build:
  stage: build
  script: ./gradlew clean build
  artifacts:
    paths:
      - build/libs/socshared-microservice-template-1.0.0-SNAPSHOT.jar

docker-build:
  stage: docker-build
  script:
    - docker build -t $CI_DOCKER_LOGIN/socshared-microservice-template .

docker-push:
  stage: docker-push
  script:
    - docker login -u "$CI_DOCKER_LOGIN" -p "$CI_DOCKER_PASSWORD"
    - docker push $CI_DOCKER_LOGIN/socshared-microservice-template

docker-deploy-swarm:
  stage: docker-deploy-swarm
  script:
    - touch .env_mail
    - echo "SPRING_PROFILE=dev" >> .env_mail
    - echo "MAIL_USERNAME=support@socshared.ml" >> .env_mail
    - echo "MAIL_PASSWORD=Admin12345" >> .env_mail
    - echo "MAIL_SMTP_HOST=smtp.mail.ru" >> .env_mail
    - echo "MAIL_FROM_EMAIL=support@socshared.ml" >> .env_mail
    - docker stack deploy -c docker-compose.yaml socshared
