image: docker:latest
services:
  - docker:dind

stages:
  - build

before_script:
  - chmod +x gradlew

build:
  stage: build
  script: ./gradlew clean build
  artifacts:
    paths:
      - build/libs/microservice-template-1.0.0-SNAPSHOT.jar
