image: java:11

stages:
  - build
  - docker-build
  - docker-push
  - docker-deploy-swarm

before_script:
  - chmod +x gradlew

build:
  stage: build
  script: ./gradlew clean build
  artifacts:
    paths:
      - build/libs/socshared-mail-sender-service-1.0.0-SNAPSHOT.jar

docker-build:
  stage: docker-build
  script:
    - docker 2>/dev/null 1>&2 rmi `docker images -aq` || true
    - docker build -t $CI_DOCKER_LOGIN/socshared-mail-sender-service .

docker-push:
  stage: docker-push
  script:
    - docker login -u "$CI_DOCKER_LOGIN" -p "$CI_DOCKER_PASSWORD"
    - docker push $CI_DOCKER_LOGIN/socshared-mail-sender-service

docker-deploy-swarm:
  stage: docker-deploy-swarm
  script:
    - touch .env_mail
    - echo "SPRING_PROFILE=dev" >> .env_mail
    - echo "MAIL_USERNAME=support@socshared.ml" >> .env_mail
    - echo "MAIL_PASSWORD=Admin12345" >> .env_mail
    - echo "MAIL_SMTP_HOST=smtp.mail.ru" >> .env_mail
    - echo "MAIL_FROM_EMAIL=support@socshared.ml" >> .env_mail
    - echo "AUTH_SERVICE=$AUTH_SERVICE" >> .env_mail
    - echo "SECRET_JWT_KEY=$SECRET_JWT_KEY" >> .env_mail
    - echo "SENTRY_DSN=https://1dd165ad49bf4228a05debb8c6927797@sentry.socshared.ml/2" >> .env_mail
    - docker stack deploy -c docker-compose.yaml socshared
