spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/name_db
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
  zipkin:
    base-url: http://zipkin:9411/
    service:
      name: ${spring.application.name}
  main:
    allow-bean-definition-overriding: true

keycloak:
  realm: dev
  auth-server-url: http://keycloak:9999/auth
  ssl-required: none
  resource: name-client-to-keycloak
  use-resource-role-mappings: false
  principal-attribute: preferred_username
  cors: true
  bearer-only: true