spring:
  zipkin:
    base-url: http://zipkin:9411/
    service:
      name: ${spring.application.name}
  main:
    allow-bean-definition-overriding: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}


mail:
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  smtp:
    host: ${MAIL_SMTP_HOST}
    socketFactoryPost: 465
    socketFactoryClass: javax.net.ssl.SSLSocketFactory
    auth: true
    port: 465
  from:
    email: ${MAIL_FROM_EMAIL}

