spring:
  zipkin:
    base-url: http://zipkin:9411/
    service:
      name: ${spring.application.name}
  main:
    allow-bean-definition-overriding: true

mail:
  username: ${MAIL_USERNAME:support@socshared.ml}
  password: ${MAIL_PASSWORD:Admin12345}
  smtp:
    host: ${MAIL_SMTP_HOST:smtp.mail.ru}
    socketFactoryPost: 465
    socketFactoryClass: javax.net.ssl.SSLSocketFactory
    auth: true
    port: 465
  from:
    email: ${MAIL_FROM_EMAIL:support@socshared.ml}