/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ml.socshared.service.mail;

import io.sentry.Sentry;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.openfeign.EnableFeignClients;

@EnableFeignClients
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
        Sentry.init("https://705caee204a947ca80c10cfe7682afff@sentry.socshared.ml/3");
    }

}
